version: '3.9'
services:
  nestapp:
    container_name: nestapp
    image: nestapp:1.0.0
    build: .
    env_file:
      - .env
    environment:
      DATABASE_TYPE: ${DATABASE_TYPE}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_SYNC: ${DATABASE_SYNC}
      JWT_ACCESS_SECRET: ${JWT_ACCESS_SECRET}
      JWT_ACCESS_EXPIRE: ${JWT_ACCESS_EXPIRE}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_REFRESH__EXPIRE: ${JWT_REFRESH__EXPIRE}
      PER_PAGE: ${PER_PAGE}
      PASSWORD_SALT_ROUNDS: ${PASSWORD_SALT_ROUNDS}
    ports:
      - 3100:3100
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:14.8-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: {}